# Function Samples Configuration
# Version control for function annotation training data

version: "1.0"
description: "Function samples for annotation training"

samples:
  v1:
    file: feedings/function_sample1.py
    type: "arithmetic_and_math"
    functions:
      count: 20
      categories:
        - arithmetic
        - geometry
        - statistics
        - linear_algebra
  
  v2:
    file: feedings/function_sample2.py
    type: "text_processing"
    functions:
      count: 20
      categories:
        - string_operations
        - text_analysis
        - data_formatting
        - encryption

metadata:
  created: "2024"
  last_updated: "2024"
  purpose: "Training data for function annotation model"

