name: CI Pipeline with Pylint Scoring
on:
  push:
    branches: [main, dev,staging]
  pull_request:
    branches: [main, dev,staging]

jobs:
  # 任务1：代码检查（Pylint 打分）
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: 安装依赖
        run: |
          pip install -r requirements.txt
          pip install pylint
      - name: 运行 Pylint 代码检查（并输出打分）
        run: pylint --score=y func_annotator.py test.py

  # 任务2：运行单元测试
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: 安装依赖
        run: pip install -r requirements.txt
      - name: 运行 pytest 测试
        run: pytest test.py -v

  # 任务3：构建 Docker 镜像
  docker-build:
    needs: [lint, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: func-annotator:latest